### ISSUE TITLE
Minified header

### ISSUE THREAD

**Issue by vedranio** [moroshko/accessible-colors#14]

**Comment by vedranio** [comment]
I've exported the design to Zeplin

**Comment by moroshko** [comment]
To fix:
1. Make transition smooth
2. When there is an input error, trying to scroll reverts the header back (because it reaches `scrollTop=0` during animation).
3. When SubHeader is hidden (in the minified header), it sits on top of the user input, so user cannot click on the input to focus.
4. Transition doesn't work in well Safari

**Comment by moroshko** [comment]
As we compressed our header, I suggest we get rid of this one.
